### ISSUE TITLE
White corners around buttons!

### ISSUE THREAD

**Issue by ghost** [ionic-team/ionic-ion-ios-buttons#1]
Hi! The buttons are really cool! @bug: The button shows white corners and makes it visible that it chopped from square shape. Please try to correct it.

Thanks in advance!!

**Comment by tvollstaedt** [comment]
@naveenkarippai1 Use a `<div>` instead of `<button>`

**Comment by adamdbradley** [comment]
Greetings @ghost!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
